CREATE TABLE pronunciation_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_word VARCHAR(256) NOT NULL,
    display_word VARCHAR(256) NOT NULL,
    ipa VARCHAR(512) NOT NULL,
    dialects VARCHAR(128) NOT NULL,
    source_url VARCHAR(1024) NOT NULL,
    source_name VARCHAR(64) NOT NULL,
    source_snapshot VARCHAR(32) NOT NULL,
    review_status VARCHAR(24) NOT NULL,
    CONSTRAINT uq_pronunciation_entry UNIQUE (normalized_word, ipa, dialects, source_url)
);

CREATE INDEX idx_pronunciation_word ON pronunciation_entry (normalized_word);
